receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: "rems-acdc"
          scrape_interval: 30s
          static_configs:
            - targets: ["localhost:9404"]   # jmx-exporter sidecar
              labels:
                service: "rems"
                instance: "acdc"
        # Enable later if REMS exposes Prometheus metrics on :3000/metrics
        # - job_name: "rems-app"
        #   scrape_interval: 30s
        #   metrics_path: /metrics
        #   static_configs:
        #     - targets: ["localhost:3000"]

exporters:
  awsprometheusremotewrite:
    endpoint: "https://aps-workspaces.${AWS_REGION}.amazonaws.com/workspaces/${AMP_WORKSPACE_ID}/api/v1/remote_write"
    aws_auth:
      region: "${AWS_REGION}"
      service: "aps"

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [awsprometheusremotewrite]
